In [2]:
import altair as alt
import pandas as pd

In [4]:
#Introducing Wide Form Data
# - WIDE FORM HAS ONE ROW PER INDEPENDENT VARIABLE, WITH META DATA RECORDED IN THE ROW AND COLUMN LABELS


wide_form = pd.DataFrame({ 'Year': [2018, 2019, 2020],
                      'Clothing' : [110, 101, 129],
                      'Furniture' : [201, 184, 195],
                      'Health' : [120, 132, 133]
                    })

wide_form

   Year  Clothing  Furniture  Health
0  2018       110        201     120
1  2019       101        184     132
2  2020       129        195     133

In [5]:
#Introducing Long Form Data
# - LONG FORM HAS ONE ROW PER OBSERVATION, WITH META DATA RECORDED WITHIN THE TABLE AS VALUES

long_form = pd.DataFrame({ 'Year': [2018, 2019, 2020,
                                    2018, 2019, 2020,
                                    2018, 2019, 2020],
                      'Category' : ['Clothing', 'Clothing', 'Clothing',
                                    'Furniture', 'Furniture', 'Furniture',
                                    'Health', 'Health', 'Health'],
                      'Sales' : [110, 101, 129,
                                 201, 184, 195,
                                 120, 132, 133]
                        })

long_form

   Year   Category  Sales
0  2018   Clothing    110
1  2019   Clothing    101
2  2020   Clothing    129
3  2018  Furniture    201
4  2019  Furniture    184
5  2020  Furniture    195
6  2018     Health    120
7  2019     Health    132
8  2020     Health    133

In [5]:
alt.Chart(long_form).mark_line().encode(
    x='Year:O',
    y='Sales:Q',
    color='Category:N'
).properties(
    height=400,
    width=600,
    title= 'Annual Sales by Product Category'
)

alt.Chart(...)

In [ ]:
#THIS CAN BE USED AS A PREPROCESSING STEP - Will look like long form data
wide_form.melt('Year', var_name='Category', value_name='Sales')

   Year   Category  Sales
0  2018   Clothing    110
1  2019   Clothing    101
2  2020   Clothing    129
3  2018  Furniture    201
4  2019  Furniture    184
5  2020  Furniture    195
6  2018     Health    120
7  2019     Health    132
8  2020     Health    133

In [6]:
alt.Chart(wide_form.melt('Year', var_name='Category', value_name='Sales')
).mark_line().encode(
    x='Year:O',
    y='Sales:Q',
    color='Category:N'
).properties(              
    height=400,
    width=600,
    title='Annual Sales by Category')

alt.Chart(...)